[package]
name = "almo-mcf-core"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rayon = { version = "1.10", optional = true }

[features]
parallel = ["dep:rayon"]
simd = []

[dev-dependencies]
