[package]
name = "almo-mcf-core"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
rayon = { workspace = true }

[features]
parallel = []
simd = []

[dev-dependencies]
approx = "0.5"
